AWSTemplateFormatVersion: '2010-09-09'
Resources:
  BashReplFunction:
    Properties:
      CodeUri: .
      Events:
        Exec:
          Properties:
            Method: GET
            Path: /api/exec/{_src}
          Type: Api
        Health:
          Properties:
            Method: GET
            Path: /api/health
          Type: Api
      Handler: bootstrap
      Runtime: provided.al2
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
